---
x-django: &django
  build:
    context: .
    dockerfile: docker/Dockerfile
  ports:
  - 8000:8000/TCP
  environment: &django-environment
    SECRET_KEY: ${SECRET_KEY}
    URL: http://localhost:8000
    CSRF_TRUSTED_ORIGINS: http://localhost:8000
    DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres/postgres
services:
  django:
    <<: *django
    profiles:
    - prod
    volumes:
    - django_media:/app/media
  django-dev:
    <<: *django
    profiles:
    - dev
    command: ./manage.py runserver 0.0.0.0:8000
    environment:
      <<: *django-environment
      DEBUG: true
    volumes:
    - ./buildher:/app/buildher
    - ./website:/app/website
    - django_media:/app/media
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - pg_data:/var/lib/postgresql/data
volumes:
  django_media: {}
  pg_data: {}
