# fly.toml app configuration file generated for buildher on 2024-01-24T00:01:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "buildher"
primary_region = "arn"
console_command = "/app/manage.py shell"

[build]
  dockerfile = "docker/Dockerfile"

[deploy]
  release_command = "/entrypoint.sh"

[env]
  CSRF_TRUSTED_ORIGINS = "https://buildher.fly.dev"
  URL = "https://buildher.fly.dev"

[mounts]
  source = "media"
  destination = "/app/media"
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "5GB"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"
